version: "3.9"  # optional since v1.27.0
services:
  torneo:
    build: .
    image: torneo
    ports:
      - 8080:8080

  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: torneo
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql

  dbadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1